### ISSUE TITLE
Idea: Using SuperMemo Plan day planner

### ISSUE THREAD

**Issue by hnvy** [siduck/TaskCrafty#2]
Hello!

I have been using [NvChad](https://github.com/NvChad/NvChad), and it's quite awesome. So... thank you for that!

I went on your GitHub profile to see if you've got any other cool projects (chadwm looks neat too), and I saw that this one was still WIP. So, I decided to make this suggestion.

I think we can agree that a large majority of task managers are rather... basic in nature: to-do list, calendar, timer, etc. Nothing particularly special. I'm not sure if you have some special idea in mind for TaskCrafty, but if not, then here is one: https://github.com/hnvy/day-ploy (an open-source rudimentary clone of the proprietry [SuperMemo Plan](https://help.supermemo.org/wiki/Plan). It has a lot of comments which will hopefully make it easier to understand).

In short, it is a day planner which asks the user to enter a list of tasks, and then asks for ratios. After that, depending on how many hours of work you want to do, it will create a perfect daily plan for you (based on the number of tasks and the ratios you assigned to each). The basic maths behind how it works is on my Google Drive (pictures): https://drive.google.com/drive/folders/11RUZw8MVdKXdb8HpuYR5epiktKPhkoOO

I had a plan (no pun intended) to create a GUI for it, but I decided to keep it minimal. Another aspiring front-end developer had some ideas for a front-end of this app (@simonlearnscoding).

P.S. I apologise for the bad code. I'm no expert unfortunately. There is a Lua version of this somewhere on my computer; I can find that for you if you prefer Lua instead of Python.

I haven't seen any other implementation of SuperMemo Plan anywhere on the web; I would love to see this one turn into something nice (the current UI looks nice, so I have no doubts/worries).

Please let me know if you have any questions or thoughts. I'd love to hear them.

Also, no hard feelings if this is not what you're looking for!

Harvey R.

**Comment by siduck** [comment]
I'm open to such cool planner ideas but i had paused development of taskcrafty because handling data from localstorage in browser felt tedious, idk backend stuff at all so i decided to continue it when i finish learning backend and would save the data in some remote db , but my bro told me to look into self-deployed stuff / localhost stuff :thinking: but idk how to do that yet.

**Comment by simonlearnscoding** [comment]
hey @siduck I know backend stuff we should get together and discuss someday @hnvy what is your current skillset/techstack

**Comment by siduck** [comment]
> hey @siduck I know backend stuff we should get together and discuss someday @hnvy what is your current skillset/techstack

honestly i dont like my codebases to have code which i cant handle or understand :grin:  , and with some planning and more features ( currently this project is just in its infancy stage ) I could make it a saas. So i'd want to do this alone. 

Depending on other devs would slow it down as i'd have to wait for y'all to show up. Once i get proper backend knowledge and experience, I'd do this myself!

**Comment by simonlearnscoding** [comment]
Do you have experience with react js and node? or python?

Am So., 4. Feb. 2024 um 02:11 Uhr schrieb Sidhanth Rathod <
***@***.***>:

**Comment by simonlearnscoding** [comment]
oh I also just now realized that you are the creator of nvchad great work your config looks awsome

**Comment by siduck** [comment]
i'm just a frontend dev so ik react, solidjs, svelte. no python or node

**Comment by siduck** [comment]
and this project's written in svelte so i wont migrate to react ever, i only use react for work's website cuz i'm forced to use (  nextjs as its a mature project )

**Comment by hnvy** [comment]
> hey @siduck I know backend stuff we should get together and discuss someday @hnvy what is your current skillset/techstack

Hello,

Unfortunately, I haven't had time to develop my coding skills since starting uni again (rudimentary Python, Lua, and C++). So, I'm of no use :'( But, if you have questions about how day-ploy works, then I'd be happy happy to answer them. The code is basic (I have only used the native libraries!) and thoroughly annotated, so I have no doubt that you can figure it out (I will find the Lua version and post it)!

This post was simply a free suggestion for siduck to use. Hopefully, one day, he can use it to develop their app into something useful and unique (Plan is super good to time management)!

All the best to you both!


HR

**Comment by siduck** [comment]
supermemoplan looks complex tho, i'll just add these sections of it, start,activity , length, status.  So not entirely of supermemoplan     but inspired by it

**Comment by simonlearnscoding** [comment]
I know node and some backend stuff if you want we can split up and I do the frontend and you the backend @siduck

**Comment by siduck** [comment]
> I know node and some backend stuff if you want we can split up and I do the frontend and you the backend @siduck

i appreciate your help but i dont want to use node/js for the backend :grin:

**Comment by simonlearnscoding** [comment]
I know next and express and python too. What stack would you like to use
for the backend

Am Di., 13. Feb. 2024 um 18:19 Uhr schrieb Sidhanth Rathod <
***@***.***>:

**Comment by siduck** [comment]
> I know next and express and python too. What stack would you like to use for the backend   

Ik next too, but the site's written in svelte and i could probably use bun  & elyssia js / golang for backend ( i need to learn it tho ). Although i have to first complete the site's UI and use localstorage temporary for it. Also i dont like python.
