### ISSUE TITLE
theme doesnt switch

### ISSUE THREAD

**Issue by pytxt** [siduck/TaskCrafty#3]
unable to switch theme from light to dark

**Comment by siduck** [comment]
@pytxt this is a just a static app for now, i will resume to it once i learn backend stuff :D

**Comment by pytxt** [comment]
@siduck plus the "Settings" button vanishes 90% while hovering on it.

**Comment by siduck** [comment]
@pytxt  ik there are bugs with this app! i made it for some interview before so its all rushed ( was learning svelte back then )
